name: Check labels

on:
  pull_request:

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: release:major,release:minor,release:patch,release:none
          repo_token: ${{ secrets.GITHUB_TOKEN }}
